insert into sih_disease (id,label,filter_kind,tabnet_code,def_path) values
('colera','Cólera','lista_morb','1','sih/cnv/nibr.def'),
('febres_tifoide_e_paratifoide','Febres tifóide e paratifóide','lista_morb','2','sih/cnv/nibr.def'),
('shiguelose','Shiguelose','lista_morb','3','sih/cnv/nibr.def'),
('amebiase','Amebíase','lista_morb','4','sih/cnv/nibr.def'),
('diarreia_e_gastroenterite_origem_infecc_presumivel','Diarréia e gastroenterite origem infecc presumível','lista_morb','5','sih/cnv/nibr.def'),
('outras_doencas_infecciosas_intestinais','Outras doenças infecciosas intestinais','lista_morb','6','sih/cnv/nibr.def'),
('tuberculose_pulmonar','Tuberculose pulmonar','lista_morb','7','sih/cnv/nibr.def'),
('outras_tuberculoses_respiratorias','Outras tuberculoses respiratórias','lista_morb','8','sih/cnv/nibr.def'),
('restante_de_tuberculose_respiratoria','Restante de tuberculose respiratória','lista_morb','9','sih/cnv/nibr.def'),
('tuberculose_do_sistema_nervoso','Tuberculose do sistema nervoso','lista_morb','10','sih/cnv/nibr.def'),
('tuberc_intest_peritonio_glangl_mesentericos','Tuberc intest peritônio glângl mesentéricos','lista_morb','11','sih/cnv/nibr.def'),
('tuberculose_ossea_e_das_articulacoes','Tuberculose óssea e das articulações','lista_morb','12','sih/cnv/nibr.def'),
('tuberculose_do_aparelho_geniturinario','Tuberculose do aparelho geniturinário','lista_morb','13','sih/cnv/nibr.def'),
('tuberculose_miliar','Tuberculose miliar','lista_morb','14','sih/cnv/nibr.def'),
('restante_de_outras_tuberculoses','Restante de outras tuberculoses','lista_morb','15','sih/cnv/nibr.def'),
('peste','Peste','lista_morb','16','sih/cnv/nibr.def'),
('brucelose','Brucelose','lista_morb','17','sih/cnv/nibr.def'),
('hanseniase_lepra','Hanseníase [lepra]','lista_morb','18','sih/cnv/nibr.def'),
('tetano_neonatal','Tétano neonatal','lista_morb','19','sih/cnv/nibr.def'),
('outros_tetanos','Outros tétanos','lista_morb','20','sih/cnv/nibr.def'),
('difteria','Difteria','lista_morb','21','sih/cnv/nibr.def'),
('coqueluche','Coqueluche','lista_morb','22','sih/cnv/nibr.def'),
('infeccao_meningococica','Infecção meningocócica','lista_morb','23','sih/cnv/nibr.def'),
('septicemia','Septicemia','lista_morb','24','sih/cnv/nibr.def'),
('leptospirose_icterohemorragica','Leptospirose icterohemorrágica','lista_morb','25','sih/cnv/nibr.def'),
('outras_formas_de_leptospirose','Outras formas de leptospirose','lista_morb','26','sih/cnv/nibr.def'),
('leptospirose_nao_especificada','Leptospirose não especificada','lista_morb','27','sih/cnv/nibr.def'),
('restante_de_outras_doencas_bacterianas','Restante de outras doenças bacterianas','lista_morb','28','sih/cnv/nibr.def'),
('sifilis_congenita','Sífilis congênita','lista_morb','29','sih/cnv/nibr.def'),
('sifilis_precoce','Sífilis precoce','lista_morb','30','sih/cnv/nibr.def'),
('outras_sifilis','Outras sífilis','lista_morb','31','sih/cnv/nibr.def'),
('infeccao_gonococica','Infecção gonocócica','lista_morb','32','sih/cnv/nibr.def'),
('doencas_por_clamidias_transmitidas_por_via_sexual','Doenças por clamídias transmitidas por via sexual','lista_morb','33','sih/cnv/nibr.def'),
('outras_infeccoes_com_transm_predominant_sexual','Outras infecções com transm predominant sexual','lista_morb','34','sih/cnv/nibr.def'),
('febres_recorrentes','Febres recorrentes','lista_morb','35','sih/cnv/nibr.def'),
('tracoma','Tracoma','lista_morb','36','sih/cnv/nibr.def'),
('tifo_exantematico','Tifo exantemático','lista_morb','37','sih/cnv/nibr.def'),
('poliomielite_aguda','Poliomielite aguda','lista_morb','38','sih/cnv/nibr.def'),
('raiva','Raiva','lista_morb','39','sih/cnv/nibr.def'),
('encefalite_viral','Encefalite viral','lista_morb','40','sih/cnv/nibr.def'),
('febre_amarela','Febre amarela','lista_morb','41','sih/cnv/nibr.def'),
('dengue_dengue_classsico','Dengue [dengue clásssico]','lista_morb','42','sih/cnv/nibr.def'),
('febre_hemorragica_devida_ao_virus_da_dengue','Febre hemorrágica devida ao vírus da dengue','lista_morb','43','sih/cnv/nibr.def'),
('restante_de_outr_febr_arbovirus_febr_hemor_virus','Restante de outr febr arbovírus febr hemor vírus','lista_morb','44','sih/cnv/nibr.def'),
('infeccoes_pelo_virus_do_herpes','Infecções pelo vírus do herpes','lista_morb','45','sih/cnv/nibr.def'),
('varicela_e_herpes_zoster','Varicela e herpes zoster','lista_morb','46','sih/cnv/nibr.def'),
('sarampo','Sarampo','lista_morb','47','sih/cnv/nibr.def'),
('rubeola','Rubéola','lista_morb','48','sih/cnv/nibr.def'),
('hepatite_aguda_b','Hepatite aguda B','lista_morb','49','sih/cnv/nibr.def'),
('outras_hepatites_virais','Outras hepatites virais','lista_morb','50','sih/cnv/nibr.def'),
('doenca_pelo_virus_da_imunodeficiencia_humana_hiv','Doença pelo vírus da imunodeficiência humana [HIV]','lista_morb','51','sih/cnv/nibr.def'),
('caxumba_parotidite_epidemica','Caxumba [parotidite epidêmica]','lista_morb','52','sih/cnv/nibr.def'),
('meningite_viral','Meningite viral','lista_morb','53','sih/cnv/nibr.def'),
('restante_de_outras_doencas_virais','Restante de outras doenças virais','lista_morb','54','sih/cnv/nibr.def'),
('micoses','Micoses','lista_morb','55','sih/cnv/nibr.def'),
('malaria_por_plasmodium_falciparum','Malária por Plasmodium falciparum','lista_morb','56','sih/cnv/nibr.def'),
('malaria_por_plasmodium_vivax','Malária por Plasmodium vivax','lista_morb','57','sih/cnv/nibr.def'),
('malaria_por_plasmodium_malariae','Malária por Plasmodium malariae','lista_morb','58','sih/cnv/nibr.def'),
('outras_formas_malaria_conf_exames_parasitolog','Outras formas malária conf exames parasitológ','lista_morb','59','sih/cnv/nibr.def'),
('malaria_nao_especificada','Malária não especificada','lista_morb','60','sih/cnv/nibr.def'),
('leishmaniose_visceral','Leishmaniose visceral','lista_morb','61','sih/cnv/nibr.def'),
('leishmaniose_cutanea','Leishmaniose cutânea','lista_morb','62','sih/cnv/nibr.def'),
('leishmaniose_cutaneo_mucosa','Leishmaniose cutâneo-mucosa','lista_morb','63','sih/cnv/nibr.def'),
('leishmaniose_nao_especificada','Leishmaniose não especificada','lista_morb','64','sih/cnv/nibr.def'),
('tripanossomiase','Tripanossomíase','lista_morb','65','sih/cnv/nibr.def'),
('esquistossomose','Esquistossomose','lista_morb','66','sih/cnv/nibr.def'),
('outras_infestacoes_por_trematodeos','Outras infestações por trematódeos','lista_morb','67','sih/cnv/nibr.def'),
('equinococose','Equinococose','lista_morb','68','sih/cnv/nibr.def'),
('dracunculiase','Dracunculíase','lista_morb','69','sih/cnv/nibr.def'),
('oncocercose','Oncocercose','lista_morb','70','sih/cnv/nibr.def'),
('filariose','Filariose','lista_morb','71','sih/cnv/nibr.def'),
('ancilostomiase','Ancilostomíase','lista_morb','72','sih/cnv/nibr.def'),
('outras_helmintiases','Outras helmintíases','lista_morb','73','sih/cnv/nibr.def'),
('sequelas_de_tuberculose','Seqüelas de tuberculose','lista_morb','74','sih/cnv/nibr.def'),
('sequelas_de_poliomielite','Seqüelas de poliomielite','lista_morb','75','sih/cnv/nibr.def'),
('sequelas_de_hanseniase_lepra','Seqüelas de hanseníase [lepra]','lista_morb','76','sih/cnv/nibr.def'),
('outras_doencas_infecciosas_e_parasitarias','Outras doenças infecciosas e parasitárias','lista_morb','77','sih/cnv/nibr.def'),
('neoplasia_maligna_do_labio_cavidade_oral_e_faringe','Neoplasia maligna do lábio cavidade oral e faringe','lista_morb','78','sih/cnv/nibr.def'),
('neoplasia_maligna_do_esofago','Neoplasia maligna do esôfago','lista_morb','79','sih/cnv/nibr.def'),
('neoplasia_maligna_do_estomago','Neoplasia maligna do estômago','lista_morb','80','sih/cnv/nibr.def')
on conflict (id) do update set label=excluded.label, filter_kind=excluded.filter_kind, tabnet_code=excluded.tabnet_code, def_path=excluded.def_path;