insert into sih_disease (id,label,filter_kind,tabnet_code,def_path) values
('neoplasia_maligna_do_colon','Neoplasia maligna do cólon','lista_morb','81','sih/cnv/nibr.def'),
('neopl_malig_juncao_retossigm_reto_anus_canal_anal','Neopl malig junção retossigm reto ânus canal anal','lista_morb','82','sih/cnv/nibr.def'),
('neopl_malig_figado_e_vias_biliares_intra_hepaticas','Neopl malig fígado e vias biliares intra-hepáticas','lista_morb','83','sih/cnv/nibr.def'),
('neoplasia_maligna_do_pancreas','Neoplasia maligna do pâncreas','lista_morb','84','sih/cnv/nibr.def'),
('outras_neoplasias_malignas_de_orgaos_digestivos','Outras neoplasias malignas de órgãos digestivos','lista_morb','85','sih/cnv/nibr.def'),
('neoplasias_malignas_de_laringe','Neoplasias malignas de laringe','lista_morb','86','sih/cnv/nibr.def'),
('neoplasia_maligna_de_traqueia_bronquios_e_pulmoes','Neoplasia maligna de traquéia brônquios e pulmões','lista_morb','87','sih/cnv/nibr.def'),
('outras_neopl_malig_org_respirat_e_intratoracicos','Outras neopl malig órg respirat e intratorácicos','lista_morb','88','sih/cnv/nibr.def'),
('neoplasia_maligna_do_osso_e_cartilagem_articular','Neoplasia maligna do osso e cartilagem articular','lista_morb','89','sih/cnv/nibr.def'),
('neoplasia_maligna_da_pele','Neoplasia maligna da pele','lista_morb','90','sih/cnv/nibr.def'),
('outras_neoplasias_malignas_da_pele','Outras neoplasias malignas da pele','lista_morb','91','sih/cnv/nibr.def'),
('neopl_malig_do_tecido_mesotelial_e_tecidos_moles','Neopl malig do tecido mesotelial e tecidos moles','lista_morb','92','sih/cnv/nibr.def'),
('neoplasia_maligna_da_mama','Neoplasia maligna da mama','lista_morb','93','sih/cnv/nibr.def'),
('neoplasia_maligna_do_colo_do_utero','Neoplasia maligna do colo do útero','lista_morb','94','sih/cnv/nibr.def'),
('neopl_malig_outr_porcoes_e_porcoes_nao_espec_utero','Neopl malig outr porções e porções não espec útero','lista_morb','95','sih/cnv/nibr.def'),
('outras_neopl_malignas_orgaos_genitais_femininos','Outras neopl malignas órgãos genitais femininos','lista_morb','96','sih/cnv/nibr.def'),
('neoplasia_maligna_da_prostata','Neoplasia maligna da próstata','lista_morb','97','sih/cnv/nibr.def'),
('outras_neopl_malignas_orgaos_genitais_masculinos','Outras neopl malignas órgãos genitais masculinos','lista_morb','98','sih/cnv/nibr.def'),
('neoplasia_maligna_da_bexiga','Neoplasia maligna da bexiga','lista_morb','99','sih/cnv/nibr.def'),
('outras_neoplasias_malignas_do_trato_urinario','Outras neoplasias malignas do trato urinário','lista_morb','100','sih/cnv/nibr.def'),
('neoplasia_maligna_dos_olhos_e_anexos','Neoplasia maligna dos olhos e anexos','lista_morb','101','sih/cnv/nibr.def'),
('neoplasia_maligna_do_encefalo','Neoplasia maligna do encéfalo','lista_morb','102','sih/cnv/nibr.def'),
('neopl_malig_outras_partes_sistema_nervoso_central','Neopl malig outras partes sistema nervoso central','lista_morb','103','sih/cnv/nibr.def'),
('neopl_malig_outr_localiz_mal_def_secun_e_nao_espec','Neopl malig outr localiz mal def secun e não espec','lista_morb','104','sih/cnv/nibr.def'),
('doenca_de_hodgkin','Doença de Hodgkin','lista_morb','105','sih/cnv/nibr.def'),
('linfoma_nao_hodgkin','Linfoma não-Hodgkin','lista_morb','106','sih/cnv/nibr.def'),
('leucemia','Leucemia','lista_morb','107','sih/cnv/nibr.def'),
('outras_neopl_malig_tecidos_linfoid_hematop_e_relac','Outras neopl malig tecidos linfóid hematop e relac','lista_morb','108','sih/cnv/nibr.def'),
('carcinoma_in_situ_de_colo_do_utero','Carcinoma in situ de colo do útero','lista_morb','109','sih/cnv/nibr.def'),
('neoplasia_benigna_da_pele','Neoplasia benigna da pele','lista_morb','110','sih/cnv/nibr.def'),
('neoplasia_benigna_da_mama','Neoplasia benigna da mama','lista_morb','111','sih/cnv/nibr.def'),
('leiomioma_do_utero','Leiomioma do útero','lista_morb','112','sih/cnv/nibr.def'),
('neoplasia_benigna_do_ovario','Neoplasia benigna do ovário','lista_morb','113','sih/cnv/nibr.def'),
('neoplasia_benigna_dos_orgaos_urinarios','Neoplasia benigna dos órgãos urinários','lista_morb','114','sih/cnv/nibr.def'),
('neopl_benig_encefalo_e_outr_part_sist_nerv_central','Neopl benig encéfalo e outr part sist nerv central','lista_morb','115','sih/cnv/nibr.def'),
('outr_neopl_in_situ_benigs_e_comport_incert_desconh','Outr neopl in situ benigs e comport incert desconh','lista_morb','116','sih/cnv/nibr.def'),
('anemia_por_deficiencia_de_ferro','Anemia por deficiência de ferro','lista_morb','117','sih/cnv/nibr.def'),
('outras_anemias','Outras anemias','lista_morb','118','sih/cnv/nibr.def'),
('afecc_hemorrag_e_outr_doenc_sang_e_org_hematopoet','Afecç hemorrág e outr doenç sang e órg hematopoét','lista_morb','119','sih/cnv/nibr.def'),
('alguns_transtornos_envolvendo_mecanismo_imunitario','Alguns transtornos envolvendo mecanismo imunitário','lista_morb','120','sih/cnv/nibr.def'),
('transtornos_tireoidianos_relac_deficiencia_de_iodo','Transtornos tireoidianos relac deficiência de iodo','lista_morb','121','sih/cnv/nibr.def'),
('tireotoxicose','Tireotoxicose','lista_morb','122','sih/cnv/nibr.def'),
('outros_transtornos_tireoidianos','Outros transtornos tireoidianos','lista_morb','123','sih/cnv/nibr.def'),
('diabetes_mellitus','Diabetes mellitus','lista_morb','124','sih/cnv/nibr.def'),
('desnutricao','Desnutrição','lista_morb','125','sih/cnv/nibr.def'),
('deficiencia_de_vitamina_a','Deficiência de vitamina A','lista_morb','126','sih/cnv/nibr.def'),
('outras_deficiencias_vitaminicas','Outras deficiências vitamínicas','lista_morb','127','sih/cnv/nibr.def'),
('sequelas_de_desnutricao_e_de_outras_defic_nutric','Seqüelas de desnutrição e de outras defic nutric','lista_morb','128','sih/cnv/nibr.def'),
('obesidade','Obesidade','lista_morb','129','sih/cnv/nibr.def'),
('deplecao_de_volume','Depleção de volume','lista_morb','130','sih/cnv/nibr.def'),
('outros_transt_endocrinos_nutricionais_metabolicos','Outros transt endócrinos nutricionais metabólicos','lista_morb','131','sih/cnv/nibr.def'),
('demencia','Demência','lista_morb','132','sih/cnv/nibr.def'),
('transt_mentais_e_comportamentais_dev_uso_de_alcool','Transt mentais e comportamentais dev uso de álcool','lista_morb','133','sih/cnv/nibr.def'),
('transt_mentais_comport_dev_uso_outr_subst_psicoat','Transt mentais comport dev uso outr subst psicoat','lista_morb','134','sih/cnv/nibr.def'),
('esquizofrenia_transt_esquizotipicos_e_delirantes','Esquizofrenia transt esquizotípicos e delirantes','lista_morb','135','sih/cnv/nibr.def'),
('transtornos_de_humor_afetivos','Transtornos de humor [afetivos]','lista_morb','136','sih/cnv/nibr.def'),
('transt_neurot_e_relacionados_com_stress_e_somatof','Transt neurót e relacionados com stress e somatof','lista_morb','137','sih/cnv/nibr.def'),
('retardo_mental','Retardo mental','lista_morb','138','sih/cnv/nibr.def'),
('outros_transtornos_mentais_e_comportamentais','Outros transtornos mentais e comportamentais','lista_morb','139','sih/cnv/nibr.def'),
('meningite_bacteriana_nao_classif_outra_parte','Meningite bacteriana não classif outra parte','lista_morb','140','sih/cnv/nibr.def'),
('meningite_em_doencas_bacters_class_outr_parte','Meningite em doenças bacters class outr parte','lista_morb','141','sih/cnv/nibr.def'),
('mening_em_doenc_infec_parasit_class_outr_part','Mening em doenç infec/parasit class outr part','lista_morb','142','sih/cnv/nibr.def'),
('mening_dev_outras_causas_e_causas_nao_especif','Mening dev outras causas e causas não especif','lista_morb','143','sih/cnv/nibr.def'),
('restante_doencas_inflamat_sist_nervoso_central','Restante doenças inflamat sist nervoso central','lista_morb','144','sih/cnv/nibr.def'),
('doenca_de_parkinson','Doença de Parkinson','lista_morb','145','sih/cnv/nibr.def'),
('doenca_de_alzheimer','Doença de Alzheimer','lista_morb','146','sih/cnv/nibr.def'),
('esclerose_multiplas','Esclerose múltiplas','lista_morb','147','sih/cnv/nibr.def'),
('epilepsia','Epilepsia','lista_morb','148','sih/cnv/nibr.def'),
('enxaqueca_e_outras_sindromes_de_algias_cefalicos','Enxaqueca e outras síndromes de algias cefálicos','lista_morb','149','sih/cnv/nibr.def'),
('acid_vascular_cerebr_isquem_transit_e_sindr_correl','Acid vascular cerebr isquêm transit e síndr correl','lista_morb','150','sih/cnv/nibr.def'),
('transtornos_dos_nervos_raizes_e_plexos_nervosos','Transtornos dos nervos raízes e plexos nervosos','lista_morb','151','sih/cnv/nibr.def'),
('paralisia_cerebral_e_outras_sindromes_paraliticas','Paralisia cerebral e outras síndromes paralíticas','lista_morb','152','sih/cnv/nibr.def'),
('outras_doencas_do_sistema_nervoso','Outras doenças do sistema nervoso','lista_morb','153','sih/cnv/nibr.def'),
('inflamacao_da_palpebra','Inflamação da pálpebra','lista_morb','154','sih/cnv/nibr.def'),
('conjuntivite_e_outros_transtornos_da_conjuntiva','Conjuntivite e outros transtornos da conjuntiva','lista_morb','155','sih/cnv/nibr.def'),
('ceratite_e_outros_transtornos_esclerotica_e_cornea','Ceratite e outros transtornos esclerótica e córnea','lista_morb','156','sih/cnv/nibr.def'),
('catarata_e_outros_transtornos_do_cristalino','Catarata e outros transtornos do cristalino','lista_morb','157','sih/cnv/nibr.def'),
('descolamentos_e_defeitos_da_retina','Descolamentos e defeitos da retina','lista_morb','158','sih/cnv/nibr.def'),
('glaucoma','Glaucoma','lista_morb','159','sih/cnv/nibr.def'),
('estrabismo','Estrabismo','lista_morb','160','sih/cnv/nibr.def')
on conflict (id) do update set label=excluded.label, filter_kind=excluded.filter_kind, tabnet_code=excluded.tabnet_code, def_path=excluded.def_path;