insert into sih_disease (id,label,filter_kind,tabnet_code,def_path) values
('transtornos_da_refracao_e_da_acomodacao','Transtornos da refração e da acomodação','lista_morb','161','sih/cnv/nibr.def'),
('cegueira_e_visao_subnormal','Cegueira e visão subnormal','lista_morb','162','sih/cnv/nibr.def'),
('outras_doencas_do_olho_e_anexos','Outras doenças do olho e anexos','lista_morb','163','sih/cnv/nibr.def'),
('otite_media_e_outr_transt_ouvido_medio_apof_mast','Otite média e outr transt ouvido médio apóf mast','lista_morb','164','sih/cnv/nibr.def'),
('perda_de_audicao','Perda de audição','lista_morb','165','sih/cnv/nibr.def'),
('outras_doencas_do_ouvido_e_da_apofise_mastoide','Outras doenças do ouvido e da apófise mastóide','lista_morb','166','sih/cnv/nibr.def'),
('febre_reumatica_aguda','Febre reumática aguda','lista_morb','167','sih/cnv/nibr.def'),
('doenca_reumatica_cronica_do_coracao','Doença reumática crônica do coração','lista_morb','168','sih/cnv/nibr.def'),
('hipertensao_essencial_primaria','Hipertensão essencial (primária)','lista_morb','169','sih/cnv/nibr.def'),
('outras_doencas_hipertensivas','Outras doenças hipertensivas','lista_morb','170','sih/cnv/nibr.def'),
('infarto_agudo_do_miocardio','Infarto agudo do miocárdio','lista_morb','171','sih/cnv/nibr.def'),
('outras_doencas_isquemicas_do_coracao','Outras doenças isquêmicas do coração','lista_morb','172','sih/cnv/nibr.def'),
('embolia_pulmonar','Embolia pulmonar','lista_morb','173','sih/cnv/nibr.def'),
('transtornos_de_conducao_e_arritmias_cardiacas','Transtornos de condução e arritmias cardíacas','lista_morb','174','sih/cnv/nibr.def'),
('insuficiencia_cardiaca','Insuficiência cardíaca','lista_morb','175','sih/cnv/nibr.def'),
('outras_doencas_do_coracao','Outras doenças do coração','lista_morb','176','sih/cnv/nibr.def'),
('hemorragia_intracraniana','Hemorragia intracraniana','lista_morb','177','sih/cnv/nibr.def'),
('infarto_cerebral','Infarto cerebral','lista_morb','178','sih/cnv/nibr.def'),
('acid_vascular_cerebr_nao_espec_hemorrag_ou_isquem','Acid vascular cerebr não espec hemorrág ou isquêm','lista_morb','179','sih/cnv/nibr.def'),
('outras_doencas_cerebrovasculares','Outras doenças cerebrovasculares','lista_morb','180','sih/cnv/nibr.def'),
('arteroesclerose','Arteroesclerose','lista_morb','181','sih/cnv/nibr.def'),
('outras_doencas_vasculares_perifericas','Outras doenças vasculares periféricas','lista_morb','182','sih/cnv/nibr.def'),
('embolia_e_trombose_arteriais','Embolia e trombose arteriais','lista_morb','183','sih/cnv/nibr.def'),
('outras_doencas_das_arterias_arteriolas_e_capilares','Outras doenças das artérias arteríolas e capilares','lista_morb','184','sih/cnv/nibr.def'),
('flebite_tromboflebite_embolia_e_trombose_venosa','Flebite tromboflebite embolia e trombose venosa','lista_morb','185','sih/cnv/nibr.def'),
('veias_varicosas_das_extremidades_inferiores','Veias varicosas das extremidades inferiores','lista_morb','186','sih/cnv/nibr.def'),
('hemorroidas','Hemorróidas','lista_morb','187','sih/cnv/nibr.def'),
('outras_doencas_do_aparelho_circulatorio','Outras doenças do aparelho circulatório','lista_morb','188','sih/cnv/nibr.def'),
('faringite_aguda_e_amigdalite_aguda','Faringite aguda e amigdalite aguda','lista_morb','189','sih/cnv/nibr.def'),
('laringite_e_traqueite_agudas','Laringite e traqueíte agudas','lista_morb','190','sih/cnv/nibr.def'),
('outras_infeccoes_agudas_das_vias_aereas_superiores','Outras infecções agudas das vias aéreas superiores','lista_morb','191','sih/cnv/nibr.def'),
('influenza_gripe','Influenza [gripe]','lista_morb','192','sih/cnv/nibr.def'),
('pneumonia','Pneumonia','lista_morb','193','sih/cnv/nibr.def'),
('bronquite_aguda_e_bronquiolite_aguda','Bronquite aguda e bronquiolite aguda','lista_morb','194','sih/cnv/nibr.def'),
('sinusite_cronica','Sinusite crônica','lista_morb','195','sih/cnv/nibr.def'),
('outras_doencas_do_nariz_e_dos_seios_paranasais','Outras doenças do nariz e dos seios paranasais','lista_morb','196','sih/cnv/nibr.def'),
('doencas_cronicas_das_amigdalas_e_das_adenoides','Doenças crônicas das amígdalas e das adenóides','lista_morb','197','sih/cnv/nibr.def'),
('outras_doencas_do_trato_respiratorio_superior','Outras doenças do trato respiratório superior','lista_morb','198','sih/cnv/nibr.def'),
('bronquite_enfisema_e_outr_doenc_pulm_obstr_cronic','Bronquite enfisema e outr doenç pulm obstr crônic','lista_morb','199','sih/cnv/nibr.def'),
('asma','Asma','lista_morb','200','sih/cnv/nibr.def'),
('bronquiectasia','Bronquiectasia','lista_morb','201','sih/cnv/nibr.def'),
('pneumoconiose','Pneumoconiose','lista_morb','202','sih/cnv/nibr.def'),
('outras_doencas_do_aparelho_respiratorio','Outras doenças do aparelho respiratório','lista_morb','203','sih/cnv/nibr.def'),
('carie_dentaria','Cárie dentária','lista_morb','204','sih/cnv/nibr.def'),
('outros_transtornos_dentes_e_estruturas_de_suporte','Outros transtornos dentes e estruturas de suporte','lista_morb','205','sih/cnv/nibr.def'),
('outr_doenc_cavidade_oral_gland_saliv_e_maxilares','Outr doenç cavidade oral glând saliv e maxilares','lista_morb','206','sih/cnv/nibr.def'),
('ulcera_gastrica_e_duodenal','Úlcera gástrica e duodenal','lista_morb','207','sih/cnv/nibr.def'),
('gastrite_e_duodenite','Gastrite e duodenite','lista_morb','208','sih/cnv/nibr.def'),
('outras_doencas_do_esofago_estomago_e_duodeno','Outras doenças do esôfago estômago e duodeno','lista_morb','209','sih/cnv/nibr.def'),
('doencas_do_apendice','Doenças do apêndice','lista_morb','210','sih/cnv/nibr.def'),
('hernia_inguinal','Hérnia inguinal','lista_morb','211','sih/cnv/nibr.def'),
('outras_hernias','Outras hérnias','lista_morb','212','sih/cnv/nibr.def'),
('doenca_de_crohn_e_colite_ulcerativa','Doença de Crohn e colite ulcerativa','lista_morb','213','sih/cnv/nibr.def'),
('ileo_paralitico_e_obstrucao_intestinal_sem_hernia','Ileo paralítico e obstrução intestinal sem hérnia','lista_morb','214','sih/cnv/nibr.def'),
('doenca_diverticular_do_intestino','Doença diverticular do intestino','lista_morb','215','sih/cnv/nibr.def'),
('outras_doencas_dos_intestinos_e_peritonio','Outras doenças dos intestinos e peritônio','lista_morb','216','sih/cnv/nibr.def'),
('doenca_alcoolica_do_figado','Doença alcoólica do fígado','lista_morb','217','sih/cnv/nibr.def'),
('outras_doencas_do_figado','Outras doenças do fígado','lista_morb','218','sih/cnv/nibr.def'),
('colelitiase_e_colecistite','Colelitíase e colecistite','lista_morb','219','sih/cnv/nibr.def'),
('pancreatite_aguda_e_outras_doencas_do_pancreas','Pancreatite aguda e outras doenças do pâncreas','lista_morb','220','sih/cnv/nibr.def'),
('outras_doencas_do_aparelho_digestivo','Outras doenças do aparelho digestivo','lista_morb','221','sih/cnv/nibr.def'),
('infeccoes_da_pele_e_do_tecido_subcutaneo','Infecções da pele e do tecido subcutâneo','lista_morb','222','sih/cnv/nibr.def'),
('outras_doencas_da_pele_e_do_tecido_subcutaneo','Outras doenças da pele e do tecido subcutâneo','lista_morb','223','sih/cnv/nibr.def'),
('artrite_reumatoide_e_outr_poliartropatias_inflamat','Artrite reumatóide e outr poliartropatias inflamat','lista_morb','224','sih/cnv/nibr.def'),
('artrose','Artrose','lista_morb','225','sih/cnv/nibr.def'),
('deformidades_adquiridas_das_articulacoes','Deformidades adquiridas das articulações','lista_morb','226','sih/cnv/nibr.def'),
('outros_transtronos_articulares','Outros transtronos articulares','lista_morb','227','sih/cnv/nibr.def'),
('doencas_sistemicas_do_tecido_conjuntivo','Doenças sistêmicas do tecido conjuntivo','lista_morb','228','sih/cnv/nibr.def'),
('transt_discais_cervic_e_outr_transt_disc_intervert','Transt discais cervic e outr transt disc intervert','lista_morb','229','sih/cnv/nibr.def'),
('outras_dorsopatias','Outras dorsopatias','lista_morb','230','sih/cnv/nibr.def'),
('transtornos_do_tecido_mole','Transtornos do tecido mole','lista_morb','231','sih/cnv/nibr.def'),
('transtornos_da_densidade_e_da_estrutura_osseas','Transtornos da densidade e da estrutura ósseas','lista_morb','232','sih/cnv/nibr.def'),
('osteomielite','Osteomielite','lista_morb','233','sih/cnv/nibr.def'),
('outras_doencas_sist_osteomuscular_e_tec_conjuntivo','Outras doenças sist osteomuscular e tec conjuntivo','lista_morb','234','sih/cnv/nibr.def'),
('sindrome_nefriticas_aguda_e_rapidamente_progressiv','Síndrome nefríticas aguda e rapidamente progressiv','lista_morb','235','sih/cnv/nibr.def'),
('outras_doencas_glomerulares','Outras doenças glomerulares','lista_morb','236','sih/cnv/nibr.def'),
('doencas_renais_tubulo_intersticiais','Doenças renais túbulo-intersticiais','lista_morb','237','sih/cnv/nibr.def'),
('insuficiencia_renal','Insuficiência renal','lista_morb','238','sih/cnv/nibr.def'),
('urolitiase','Urolitíase','lista_morb','239','sih/cnv/nibr.def'),
('cistite','Cistite','lista_morb','240','sih/cnv/nibr.def')
on conflict (id) do update set label=excluded.label, filter_kind=excluded.filter_kind, tabnet_code=excluded.tabnet_code, def_path=excluded.def_path;