insert into sih_disease (id,label,filter_kind,tabnet_code,def_path) values
('outras_doencas_do_aparelho_urinario','Outras doenças do aparelho urinário','lista_morb','241','sih/cnv/nibr.def'),
('hiperplasia_da_prostata','Hiperplasia da próstata','lista_morb','242','sih/cnv/nibr.def'),
('outros_transtornos_da_prostata','Outros transtornos da próstata','lista_morb','243','sih/cnv/nibr.def'),
('hidrocele_e_espermatocele','Hidrocele e espermatocele','lista_morb','244','sih/cnv/nibr.def'),
('preprucio_redundante_fimose_e_parafimose','Preprúcio redundante fimose e parafimose','lista_morb','245','sih/cnv/nibr.def'),
('outras_doencas_dos_orgaos_genitais_masculinos','Outras doenças dos órgãos genitais masculinos','lista_morb','246','sih/cnv/nibr.def'),
('transtornos_da_mama','Transtornos da mama','lista_morb','247','sih/cnv/nibr.def'),
('salpingite_e_ooforite','Salpingite e ooforite','lista_morb','248','sih/cnv/nibr.def'),
('doenca_inflamatoria_do_colo_do_utero','Doença inflamatória do colo do útero','lista_morb','249','sih/cnv/nibr.def'),
('outras_doencas_inflamat_orgaos_pelvicos_femininos','Outras doenças inflamat órgãos pélvicos femininos','lista_morb','250','sih/cnv/nibr.def'),
('endometriose','Endometriose','lista_morb','251','sih/cnv/nibr.def'),
('prolapso_genital_feminino','Prolapso genital feminino','lista_morb','252','sih/cnv/nibr.def'),
('transt_nao_inflam_ovario_tromp_falopio_ligam_largo','Transt não-inflam ovário tromp Falópio ligam largo','lista_morb','253','sih/cnv/nibr.def'),
('transtornos_da_menstruacao','Transtornos da menstruação','lista_morb','254','sih/cnv/nibr.def'),
('transt_menopausicos_e_outr_transt_perimenopausicos','Transt menopáusicos e outr transt perimenopáusicos','lista_morb','255','sih/cnv/nibr.def'),
('infertilidade_feminina','Infertilidade feminina','lista_morb','256','sih/cnv/nibr.def'),
('outros_transtornos_do_aparelho_geniturinario','Outros transtornos do aparelho geniturinário','lista_morb','257','sih/cnv/nibr.def'),
('aborto_espontaneo','Aborto espontâneo','lista_morb','258','sih/cnv/nibr.def'),
('aborto_por_razoes_medicas','Aborto por razões médicas','lista_morb','259','sih/cnv/nibr.def'),
('outras_gravidezes_que_terminam_em_aborto','Outras gravidezes que terminam em aborto','lista_morb','260','sih/cnv/nibr.def'),
('edema_protein_transt_hipertens_gravid_parto_puerp','Edema protein transt hipertens gravid parto puerp','lista_morb','261','sih/cnv/nibr.def'),
('placent_prev_descol_premat_placent_hemorr_antepart','Placent prév descol premat placent hemorr antepart','lista_morb','262','sih/cnv/nibr.def'),
('outr_mot_ass_a_mae_rel_cav_fetal_amn_pos_prob_part','Outr mot ass à mãe rel cav fetal amn pos prob part','lista_morb','263','sih/cnv/nibr.def'),
('trabalho_de_parto_obstruido','Trabalho de parto obstruído','lista_morb','264','sih/cnv/nibr.def'),
('hemorragia_pos_parto','Hemorragia pós-parto','lista_morb','265','sih/cnv/nibr.def'),
('outras_complicacoes_da_gravidez_e_do_parto','Outras complicações da gravidez e do parto','lista_morb','266','sih/cnv/nibr.def'),
('parto_unico_espontaneo','Parto único espontâneo','lista_morb','267','sih/cnv/nibr.def'),
('compl_pred_rel_puerperio_e_outr_afecc_obstetr_ncop','Compl pred rel puerpério e outr afecç obstétr NCOP','lista_morb','268','sih/cnv/nibr.def'),
('feto_e_rec_nasc_afet_fat_mat_e_compl_grav_e_parto','Feto e rec-nasc afet fat mat e compl grav e parto','lista_morb','269','sih/cnv/nibr.def'),
('ret_cres_fet_desn_fet_tran_rel_gest_curt_baix_peso','Ret cres fet desn fet tran rel gest curt baix peso','lista_morb','270','sih/cnv/nibr.def'),
('trauma_durante_o_nascimento','Trauma durante o nascimento','lista_morb','271','sih/cnv/nibr.def'),
('hipoxia_intrauterina_e_asfixia_ao_nascer','Hipóxia intrauterina e asfixia ao nascer','lista_morb','272','sih/cnv/nibr.def'),
('outros_transt_respiratorios_orig_periodo_perinatal','Outros transt respiratórios orig período perinatal','lista_morb','273','sih/cnv/nibr.def'),
('doencas_infecciosas_e_parasitarias_congenitas','Doenças infecciosas e parasitárias congênitas','lista_morb','274','sih/cnv/nibr.def'),
('outras_infeccoes_especificas_do_periodo_perinatal','Outras infecções específicas do período perinatal','lista_morb','275','sih/cnv/nibr.def'),
('doenca_hemolitica_do_feto_e_do_recem_nascido','Doença hemolítica do feto e do recém-nascido','lista_morb','276','sih/cnv/nibr.def'),
('outras_afeccoes_originadas_no_periodo_perinatal','Outras afecções originadas no período perinatal','lista_morb','277','sih/cnv/nibr.def'),
('espinha_bifida','Espinha bífida','lista_morb','278','sih/cnv/nibr.def'),
('outras_malformacoes_congenitas_do_sistema_nervoso','Outras malformações congênitas do sistema nervoso','lista_morb','279','sih/cnv/nibr.def'),
('malformacoes_congenitas_do_aparelho_circulatorio','Malformações congênitas do aparelho circulatório','lista_morb','280','sih/cnv/nibr.def'),
('fenda_labial_e_fenda_palatina','Fenda labial e fenda palatina','lista_morb','281','sih/cnv/nibr.def'),
('ausencia_atresia_e_estenose_do_intestino_delgado','Ausência atresia e estenose do intestino delgado','lista_morb','282','sih/cnv/nibr.def'),
('outras_malformacoes_congenitas_aparelho_digestivo','Outras malformações congênitas aparelho digestivo','lista_morb','283','sih/cnv/nibr.def'),
('testiculo_nao_descido','Testiculo não-descido','lista_morb','284','sih/cnv/nibr.def'),
('outras_malformacoes_do_aparelho_geniturinario','Outras malformações do aparelho geniturinário','lista_morb','285','sih/cnv/nibr.def'),
('deformidades_congenitas_do_quadril','Deformidades congênitas do quadril','lista_morb','286','sih/cnv/nibr.def'),
('deformidades_congenitas_dos_pes','Deformidades congênitas dos pés','lista_morb','287','sih/cnv/nibr.def'),
('outr_malform_e_deform_congenit_aparelho_osteomusc','Outr malform e deform congênit aparelho osteomusc','lista_morb','288','sih/cnv/nibr.def'),
('outras_malformacoes_congenitas','Outras malformações congênitas','lista_morb','289','sih/cnv/nibr.def'),
('anomalias_cromossomicas_ncop','Anomalias cromossômicas NCOP','lista_morb','290','sih/cnv/nibr.def'),
('dor_abdominal_e_pelvica','Dor abdominal e pélvica','lista_morb','291','sih/cnv/nibr.def'),
('febre_de_origem_desconhecida','Febre de origem desconhecida','lista_morb','292','sih/cnv/nibr.def'),
('senilidade','Senilidade','lista_morb','293','sih/cnv/nibr.def'),
('outr_sist_sinais_achad_anorm_ex_clin_laborat_ncop','Outr sist sinais achad anorm ex clín laborat NCOP','lista_morb','294','sih/cnv/nibr.def'),
('fratura_do_cranio_e_dos_ossos_da_face','Fratura do crânio e dos ossos da face','lista_morb','295','sih/cnv/nibr.def'),
('fratura_do_pescoco_torax_ou_pelve','Fratura do pescoço tórax ou pelve','lista_morb','296','sih/cnv/nibr.def'),
('fratura_do_femur','Fratura do fêmur','lista_morb','297','sih/cnv/nibr.def'),
('fratura_de_outros_ossos_dos_membros','Fratura de outros ossos dos membros','lista_morb','298','sih/cnv/nibr.def'),
('fraturas_envolvendo_multiplas_regioes_do_corpo','Fraturas envolvendo múltiplas regiões do corpo','lista_morb','299','sih/cnv/nibr.def'),
('luxacoes_entorse_distensao_reg_esp_e_multip_corpo','Luxações entorse distensão reg esp e múltip corpo','lista_morb','300','sih/cnv/nibr.def'),
('traumatismo_do_olho_e_da_orbita_ocular','Traumatismo do olho e da órbita ocular','lista_morb','301','sih/cnv/nibr.def'),
('traumatismo_intracraniano','Traumatismo intracraniano','lista_morb','302','sih/cnv/nibr.def'),
('traumatismo_de_outros_orgaos_internos','Traumatismo de outros órgãos internos','lista_morb','303','sih/cnv/nibr.def'),
('lesoes_esmag_amput_traumat_reg_esp_e_multip_corpo','Lesões esmag amput traumát reg esp e múltip corpo','lista_morb','304','sih/cnv/nibr.def'),
('outr_traum_reg_espec_nao_espec_e_multiplas_corpo','Outr traum reg espec não espec e múltiplas corpo','lista_morb','305','sih/cnv/nibr.def'),
('efeitos_corpo_estranho_atraves_de_orificio_natural','Efeitos corpo estranho através de orifício natural','lista_morb','306','sih/cnv/nibr.def'),
('queimadura_e_corrosoes','Queimadura e corrosões','lista_morb','307','sih/cnv/nibr.def'),
('envenenamento_por_drogas_e_substancias_biologicas','Envenenamento por drogas e substâncias biológicas','lista_morb','308','sih/cnv/nibr.def'),
('efeitos_toxicos_subst_origem_princ_nao_medicinal','Efeitos tóxicos subst origem princ não-medicinal','lista_morb','309','sih/cnv/nibr.def'),
('sindromes_de_maus_tratos','Síndromes de maus tratos','lista_morb','310','sih/cnv/nibr.def'),
('outros_efeitos_e_nao_espec_de_causas_externas','Outros efeitos e não espec de causas externas','lista_morb','311','sih/cnv/nibr.def'),
('cert_compl_prec_traum_compl_cirurg_ass_medic_ncop','Cert compl prec traum compl cirúrg ass médic NCOP','lista_morb','312','sih/cnv/nibr.def'),
('sequel_traum_enven_e_outr_conseq_causas_externas','Seqüel traum enven e outr conseq causas externas','lista_morb','313','sih/cnv/nibr.def'),
('pessoas_em_contato_com_serv_saude_exame_e_investig','Pessoas em contato com serv saúde exame e investig','lista_morb','314','sih/cnv/nibr.def'),
('estado_infec_assint_virus_da_imunodef_humana_hiv','Estado infec assint vírus da imunodef humana [HIV]','lista_morb','315','sih/cnv/nibr.def'),
('outr_pess_riscos_pot_a_saude_rel_doencas_transmiss','Outr pess riscos pot à saúde rel doenças transmiss','lista_morb','316','sih/cnv/nibr.def'),
('anticoncepcao','Anticoncepção','lista_morb','317','sih/cnv/nibr.def'),
('rastreamento_pre_natal_e_outr_superv_da_gravidez','Rastreamento pré-natal e outr superv da gravidez','lista_morb','318','sih/cnv/nibr.def'),
('nascidos_vivos_segundo_o_local_de_nascimento','Nascidos vivos segundo o local de nascimento','lista_morb','319','sih/cnv/nibr.def'),
('assistencia_e_exame_pos_natal','Assistência e exame pós-natal','lista_morb','320','sih/cnv/nibr.def')
on conflict (id) do update set label=excluded.label, filter_kind=excluded.filter_kind, tabnet_code=excluded.tabnet_code, def_path=excluded.def_path;