/**
 * Fail-closed catalog validation (D-05 / D-06 / D-10).
 * Zero new deps — hand checks only.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { CATALOG_OUT_DIR, ROOT } from './paths.mjs';
import { checkSnapshotIntegrity, slugify } from './listaMorbSource.mjs';
import { generateFromSnapshot } from './sync-lista-morb.mjs';

const DISEASES_JSON_PATH = path.join(ROOT, 'scripts/catalog/diseases.json');
const DISEASES_LISTA_JSON_PATH = path.join(ROOT, 'src/features/catalog/diseases.lista.json');

/** Standard columns generated by syncColumnMap.mjs (D2 — kept in sync by hand, not imported,
 * since syncColumnMap.mjs has top-level disk reads and is not a side-effect-free module). */
const STANDARD_COLUMNS = [
  { col: 'internacoes', idSuffix: 'internacoes', labelPrefix: 'Internações' },
  { col: 'obitos', idSuffix: 'obitos', labelPrefix: 'Óbitos' },
  { col: 'valor_total', idSuffix: 'custo', labelPrefix: 'Custo (valor total)' },
  { col: 'dias_permanencia', idSuffix: 'dias_permanencia', labelPrefix: 'Dias de permanência' },
  { col: 'taxa_mortalidade', idSuffix: 'taxa_mortalidade', labelPrefix: 'Taxa de mortalidade hospitalar' },
];
const STANDARD_COLUMN_NAMES = new Set(STANDARD_COLUMNS.map((c) => c.col));

const VARIABLE_TYPES = new Set([
  'categorica',
  'numerica',
  'ordinal',
  'taxa',
  'contagem',
  'texto',
]);

const REQUIRED_STRING_FIELDS = [
  'id',
  'label',
  'variableType',
  'domain',
  'sourceSystem',
  'sourceName',
  'tableOrIndicator',
  'period',
  'officialUrl',
  'methodologyNotes',
];

const OFFICIAL_URL_RE = /^https?:\/\//i;

/** Shared CNES/pop columns that must agree across packs when both present (RESEARCH A2). */
export const DEFAULT_SHARED_METRIC_KEYS = [
  'medicos_vasculares_sus',
  'populacao',
  'medicos_vasculares_por_100k',
];

/**
 * @param {unknown} entry
 * @param {Record<string, { packId?: string, metricKeys?: string[], rows?: unknown[] }>} packsById
 * @returns {string[]}
 */
export function checkEntry(entry, packsById = {}) {
  const errors = [];
  if (entry == null || typeof entry !== 'object' || Array.isArray(entry)) {
    return ['entry: must be a non-null object'];
  }
  /** @type {Record<string, unknown>} */
  const e = /** @type {Record<string, unknown>} */ (entry);
  const id = typeof e.id === 'string' && e.id.trim() ? e.id.trim() : '(missing id)';

  for (const field of REQUIRED_STRING_FIELDS) {
    const value = e[field];
    if (typeof value !== 'string' || value.trim().length === 0) {
      errors.push(`${id}: missing or empty required field "${field}"`);
    }
  }

  if (typeof e.variableType === 'string' && !VARIABLE_TYPES.has(e.variableType)) {
    errors.push(
      `${id}: invalid variableType "${e.variableType}" (expected one of ${[...VARIABLE_TYPES].join('|')})`,
    );
  }

  if (typeof e.loadable !== 'boolean') {
    errors.push(`${id}: loadable must be a boolean`);
  }

  if (typeof e.officialUrl === 'string' && e.officialUrl.trim().length > 0) {
    if (!OFFICIAL_URL_RE.test(e.officialUrl.trim())) {
      errors.push(
        `${id}: officialUrl must be absolute http(s) URL (got "${e.officialUrl}")`,
      );
    }
  }

  if (e.loadable === true) {
    const packId = typeof e.packId === 'string' ? e.packId.trim() : '';
    const columnKey = typeof e.columnKey === 'string' ? e.columnKey.trim() : '';
    if (!packId || !columnKey) {
      errors.push(
        `${id}: loadable:true requires packId and columnKey`,
      );
    } else {
      const pack = packsById[packId];
      if (!pack) {
        errors.push(`${id}: loadable packId "${packId}" not found in packs`);
      } else {
        const metricKeys = Array.isArray(pack.metricKeys) ? pack.metricKeys : [];
        if (!metricKeys.includes(columnKey)) {
          // Also accept presence on first row keys for resilience
          const row0 =
            Array.isArray(pack.rows) && pack.rows[0] && typeof pack.rows[0] === 'object'
              ? /** @type {Record<string, unknown>} */ (pack.rows[0])
              : null;
          const onRow = row0 != null && Object.prototype.hasOwnProperty.call(row0, columnKey);
          if (!onRow) {
            errors.push(
              `${id}: columnKey "${columnKey}" absent from pack "${packId}" metricKeys`,
            );
          }
        }
      }
    }
  }

  return errors;
}

/**
 * @param {{
 *   variables: unknown[],
 *   packsById: Record<string, any>,
 *   sharedMetricKeys?: string[],
 * }} bundle
 * @returns {{ ok: boolean, errors: string[], warnings: string[] }}
 */
export function checkCatalog(bundle) {
  const errors = [];
  const warnings = [];
  const variables = Array.isArray(bundle?.variables) ? bundle.variables : null;
  if (!variables) {
    return { ok: false, errors: ['variables: must be an array'], warnings };
  }
  const packsById =
    bundle?.packsById && typeof bundle.packsById === 'object' ? bundle.packsById : {};
  const sharedMetricKeys = Array.isArray(bundle?.sharedMetricKeys)
    ? bundle.sharedMetricKeys
    : DEFAULT_SHARED_METRIC_KEYS;

  const seen = new Map();
  for (let i = 0; i < variables.length; i++) {
    const entry = variables[i];
    const id =
      entry && typeof entry === 'object' && typeof entry.id === 'string'
        ? entry.id
        : `index:${i}`;
    if (seen.has(id)) {
      errors.push(
        `duplicate catalog id "${id}" (indices ${seen.get(id)} and ${i})`,
      );
    } else {
      seen.set(id, i);
    }
    errors.push(...checkEntry(entry, packsById));
  }

  errors.push(...checkSharedMetricsAcrossPacks(packsById, sharedMetricKeys));

  return { ok: errors.length === 0, errors, warnings };
}

/**
 * @param {Record<string, any>} packsById
 * @param {string[]} sharedMetricKeys
 * @returns {string[]}
 */
export function checkSharedMetricsAcrossPacks(packsById, sharedMetricKeys) {
  const errors = [];
  const packIds = Object.keys(packsById);
  if (packIds.length < 2) return errors;

  for (const metricKey of sharedMetricKeys) {
    const holders = packIds.filter((pid) => {
      const pack = packsById[pid];
      const keys = Array.isArray(pack?.metricKeys) ? pack.metricKeys : [];
      return keys.includes(metricKey);
    });
    if (holders.length < 2) continue;

    /** @type {Map<string, { packId: string, value: unknown }>} */
    const baseline = new Map();
    const firstId = holders[0];
    const firstPack = packsById[firstId];
    for (const row of firstPack.rows || []) {
      if (!row || typeof row !== 'object') continue;
      const key = `${String(row.uf_codigo)}|${String(row.ano)}`;
      baseline.set(key, { packId: firstId, value: row[metricKey] });
    }

    for (let h = 1; h < holders.length; h++) {
      const otherId = holders[h];
      const otherPack = packsById[otherId];
      for (const row of otherPack.rows || []) {
        if (!row || typeof row !== 'object') continue;
        const key = `${String(row.uf_codigo)}|${String(row.ano)}`;
        const base = baseline.get(key);
        if (!base) continue;
        if (!sameNumericOrNull(base.value, row[metricKey])) {
          errors.push(
            `shared metric "${metricKey}" diverges at ${key}: ${base.packId}=${JSON.stringify(base.value)} vs ${otherId}=${JSON.stringify(row[metricKey])}`,
          );
          // One sample per metric is enough to fail closed without flooding stderr
          break;
        }
      }
    }
  }

  return errors;
}

/**
 * @param {unknown} a
 * @param {unknown} b
 */
function sameNumericOrNull(a, b) {
  if (a === b) return true;
  if (a == null && b == null) return true;
  if (typeof a === 'number' && typeof b === 'number') {
    if (Number.isNaN(a) && Number.isNaN(b)) return true;
    return Object.is(a, b);
  }
  return false;
}

/**
 * Invariante A (D-10, TAX-02): `slugify(label, tabnetCode) === id` para toda entrada,
 * exceto as presentes em `allowlist` (derivada de `extra-diseases.json` pelo chamador —
 * nunca um array literal aqui). Pega gerador errado (ex.: dicionario `KNOWN_BY_CODE`
 * legado): id nao deriva do rotulo real.
 *
 * @param {{ id: string, label: string, tabnetCode: string }[]} diseases
 * @param {Iterable<string>} allowlist ids explicitamente isentos, com motivo registrado
 * @returns {string[]}
 */
export function checkSlugConsistency(diseases, allowlist = []) {
  const allowSet = allowlist instanceof Set ? allowlist : new Set(allowlist);
  const errors = [];
  for (const entry of diseases) {
    if (allowSet.has(entry.id)) continue;
    const expected = slugify(entry.label, entry.tabnetCode);
    if (expected !== entry.id) {
      errors.push(
        `${entry.id}: slugify(label, tabnetCode) !== id (esperado "${expected}", tabnetCode ${entry.tabnetCode})`,
      );
    }
  }
  return errors;
}

/**
 * @param {string} a
 * @param {string} b
 * @returns {number} offset (em caracteres) do primeiro ponto de divergencia
 */
function firstDiffOffset(a, b) {
  const len = Math.min(a.length, b.length);
  let i = 0;
  while (i < len && a[i] === b[i]) i++;
  return i;
}

/**
 * @param {string} label
 * @param {string} committedText
 * @param {string} generatedText
 * @returns {string}
 */
function regenerationDiffMessage(label, committedText, generatedText) {
  const offset = firstDiffOffset(committedText, generatedText);
  const radius = 20;
  const committedExcerpt = committedText.slice(Math.max(0, offset - radius), offset + radius);
  const generatedExcerpt = generatedText.slice(Math.max(0, offset - radius), offset + radius);
  return `${label}: diverge da regeneracao a partir do snapshot no offset ${offset} — commitado="...${committedExcerpt}..." gerado="...${generatedExcerpt}..."`;
}

/**
 * Invariante B (D-10/D-16, TAX-06): regerar do snapshot produz, string a string, o mesmo
 * texto commitado — para os dois artefatos derivados, cada um na sua formatacao (D-16):
 * `diseases.json` indentado, `diseases.lista.json` minificado numa linha. Pega edicao a
 * mao e derivado dessincronizado; a assimetria de formatacao entre os dois arquivos e
 * intencional e precisa continuar coberta.
 *
 * @param {{ diseasesText: string, listaText: string }} committed textos lidos do repo
 * @param {{ diseasesText: string, listaText: string }} generated textos de `generateFromSnapshot()`
 * @returns {string[]}
 */
export function checkRegeneration(committed, generated) {
  const errors = [];
  const committedDiseasesText = committed?.diseasesText ?? '';
  const generatedDiseasesText = generated?.diseasesText ?? '';
  if (committedDiseasesText !== generatedDiseasesText) {
    errors.push(
      regenerationDiffMessage('diseases.json', committedDiseasesText, generatedDiseasesText),
    );
  }

  const committedListaText = committed?.listaText ?? '';
  const generatedListaText = generated?.listaText ?? '';
  if (committedListaText !== generatedListaText) {
    errors.push(
      regenerationDiffMessage('diseases.lista.json', committedListaText, generatedListaText),
    );
  }

  return errors;
}

/**
 * Wrapper fino de `checkRegeneration`: le os dois artefatos commitados do disco e regera
 * do snapshot. Ainda nao e chamado de `main()` nesta plan — a plan 08-06 liga (D-24).
 *
 * @returns {string[]}
 */
export function checkRegenerationFromDisk() {
  const committed = {
    diseasesText: fs.readFileSync(DISEASES_JSON_PATH, 'utf8'),
    listaText: fs.readFileSync(DISEASES_LISTA_JSON_PATH, 'utf8'),
  };
  const generated = generateFromSnapshot();
  return checkRegeneration(committed, generated);
}

/**
 * Invariante D (D-14): particao completa entre o snapshot da Lista Morb e a taxonomia.
 * Toda opcao do snapshot ou vira agravo (tabnetCode presente em `diseases`) ou tem motivo
 * registrado em `exclusions`, nunca as duas coisas. Todo `tabnetCode` de `diseases`
 * ausente do snapshot precisa vir de `extras` (segunda fonte de entrada, D-14 — ver
 * `extra-diseases.json`). Codigo novo no TabNet, sem entrar em nenhum dos tres, falha
 * alto em vez de entrar/sair em silencio.
 *
 * @param {{
 *   options: { code: string, label: string }[],
 *   exclusions: Record<string, string>,
 *   diseases: { id: string, tabnetCode: string }[],
 *   extras: { tabnetCode: string }[],
 * }} input
 * @returns {string[]}
 */
export function checkPartition({ options, exclusions, diseases, extras }) {
  const errors = [];
  const diseaseCodes = new Set(diseases.map((d) => d.tabnetCode));
  const extraCodes = new Set(extras.map((e) => e.tabnetCode));

  for (const opt of options) {
    const code = String(opt.code).trim();
    const inDiseases = diseaseCodes.has(code);
    const inExclusions = Object.prototype.hasOwnProperty.call(exclusions, code);

    if (inDiseases && inExclusions) {
      errors.push(
        `tabnetCode ${code}: presente em diseases e em exclusions.json ao mesmo tempo — particao violada`,
      );
    } else if (!inDiseases && !inExclusions) {
      errors.push(
        `tabnetCode ${code}: ausente de diseases e de exclusions.json — particao incompleta`,
      );
    }

    if (inExclusions) {
      const reason = exclusions[code];
      if (typeof reason !== 'string' || reason.trim().length === 0) {
        errors.push(`tabnetCode ${code}: motivo vazio em exclusions.json`);
      }
    }
  }

  const optionCodes = new Set(options.map((o) => String(o.code).trim()));
  for (const disease of diseases) {
    const code = disease.tabnetCode;
    if (!optionCodes.has(code) && !extraCodes.has(code)) {
      errors.push(
        `tabnetCode ${code} (id "${disease.id}"): presente em diseases mas ausente do snapshot e de extra-diseases.json`,
      );
    }
  }

  return errors;
}

/**
 * Extensao D2: `columnMap.json` e dado, nao codigo-fonte — o invariante F (varredura de
 * repositorio) nao alcanca. `syncColumnMap.mjs` faz merge incremental e nunca remove
 * chave, entao chaves tombstone sobrevivem a um rename sem este invariante. Checa: toda
 * chave de nivel 1 casa `sih.<id>_uf` com `id` presente em `diseases`; todo agravo
 * `lista_morb` tem chave; para as cinco colunas padrao presentes, `id` e `label` da folha
 * batem com o agravo canonico daquela chave; colunas fora do padrao so tem o prefixo de
 * `id` checado (segmento do meio precisa ser o id do agravo).
 *
 * @param {Record<string, Record<string, { id?: string, label?: string }>>} columnMap
 * @param {{ id: string, label: string, filterKind: string }[]} diseases
 * @returns {string[]}
 */
export function checkColumnMapKeys(columnMap, diseases) {
  if (columnMap == null || typeof columnMap !== 'object' || Array.isArray(columnMap)) {
    return ['columnMap: deve ser um objeto'];
  }

  const errors = [];
  const diseasesById = new Map(diseases.map((d) => [d.id, d]));
  const listaMorbIds = diseases.filter((d) => d.filterKind === 'lista_morb').map((d) => d.id);
  const keyRe = /^sih\.(.+)_uf$/;

  for (const key of Object.keys(columnMap)) {
    const match = key.match(keyRe);
    const diseaseId = match ? match[1] : null;
    const disease = diseaseId ? diseasesById.get(diseaseId) : undefined;

    if (!match || !disease) {
      errors.push(
        `columnMap: chave "${key}" nao corresponde a nenhum agravo em diseases — possivel chave tombstone`,
      );
      continue;
    }

    const pack = columnMap[key] ?? {};

    for (const { col, idSuffix, labelPrefix } of STANDARD_COLUMNS) {
      const leaf = pack[col];
      if (!leaf) continue;
      const expectedId = `sih.${diseaseId}.${idSuffix}`;
      if (leaf.id !== expectedId) {
        errors.push(
          `columnMap["${key}"].${col}: id "${leaf.id}" esperado "${expectedId}"`,
        );
      }
      const expectedLabel = `${labelPrefix} — ${disease.label}`;
      if (leaf.label !== expectedLabel) {
        errors.push(
          `columnMap["${key}"].${col}: label "${leaf.label}" esperado "${expectedLabel}" — rotulo nao corresponde ao agravo canonico`,
        );
      }
    }

    for (const [col, leaf] of Object.entries(pack)) {
      if (STANDARD_COLUMN_NAMES.has(col)) continue;
      const id = leaf?.id;
      if (typeof id === 'string' && id.startsWith('sih.')) {
        const middle = id.split('.')[1];
        if (middle !== diseaseId) {
          errors.push(
            `columnMap["${key}"].${col}: id "${id}" nao referencia o agravo "${diseaseId}" desta chave`,
          );
        }
      }
    }
  }

  for (const id of listaMorbIds) {
    const key = `sih.${id}_uf`;
    if (!columnMap[key]) {
      errors.push(`columnMap: agravo lista_morb "${id}" sem chave "${key}"`);
    }
  }

  return errors;
}

/**
 * @param {string} catalogDir
 */
export function loadCatalogBundle(catalogDir) {
  const variablesPath = path.join(catalogDir, 'variables.json');
  const manifestPath = path.join(catalogDir, 'manifest.json');
  if (!fs.existsSync(variablesPath)) {
    throw new Error(`Missing ${variablesPath}`);
  }
  if (!fs.existsSync(manifestPath)) {
    throw new Error(`Missing ${manifestPath}`);
  }

  const variables = JSON.parse(fs.readFileSync(variablesPath, 'utf8'));
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  const packsById = {};

  const packRefs = Array.isArray(manifest?.packs) ? manifest.packs : [];
  for (const ref of packRefs) {
    const packId = ref?.packId;
    if (typeof packId !== 'string' || !packId) continue;
    const packPath = path.join(catalogDir, 'packs', `${packId}.json`);
    if (!fs.existsSync(packPath)) {
      throw new Error(`Missing pack file for "${packId}": ${packPath}`);
    }
    packsById[packId] = JSON.parse(fs.readFileSync(packPath, 'utf8'));
  }

  // Also load any extra pack JSON files present on disk
  const packsDir = path.join(catalogDir, 'packs');
  if (fs.existsSync(packsDir)) {
    for (const name of fs.readdirSync(packsDir)) {
      if (!name.endsWith('.json')) continue;
      const packId = name.slice(0, -'.json'.length);
      if (packsById[packId]) continue;
      packsById[packId] = JSON.parse(
        fs.readFileSync(path.join(packsDir, name), 'utf8'),
      );
    }
  }

  return { variables, manifest, packsById };
}

/**
 * @param {string} [catalogDir]
 */
export function validateCatalogDir(catalogDir = CATALOG_OUT_DIR) {
  const bundle = loadCatalogBundle(catalogDir);
  const result = checkCatalog({
    variables: bundle.variables,
    packsById: bundle.packsById,
  });

  if (
    bundle.manifest &&
    typeof bundle.manifest.catalogEntryCount === 'number' &&
    Array.isArray(bundle.variables) &&
    bundle.manifest.catalogEntryCount !== bundle.variables.length
  ) {
    result.errors.push(
      `manifest.catalogEntryCount (${bundle.manifest.catalogEntryCount}) !== variables.length (${bundle.variables.length})`,
    );
    result.ok = false;
  }

  return result;
}

function main() {
  try {
    const result = validateCatalogDir(CATALOG_OUT_DIR);
    const snapshotErrors = checkSnapshotIntegrity();
    if (snapshotErrors.length > 0) {
      result.errors.push(...snapshotErrors);
      result.ok = false;
    }
    if (!result.ok) {
      const preview = result.errors.slice(0, 25);
      console.error('catalog:validate FAILED — fail-closed (D-05/D-06)');
      for (const err of preview) {
        console.error(`  - ${err}`);
      }
      if (result.errors.length > preview.length) {
        console.error(`  … and ${result.errors.length - preview.length} more`);
      }
      process.exit(1);
    }
    console.log(
      `catalog:validate OK (${CATALOG_OUT_DIR}) — provenance gate passed`,
    );
    process.exit(0);
  } catch (err) {
    console.error('catalog:validate FAILED:', err instanceof Error ? err.message : err);
    process.exit(1);
  }
}

const isDirectRun =
  process.argv[1] &&
  import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href;

if (isDirectRun) {
  main();
}
